/* Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms. */

let fb1 = 0;
let fb2 = 1;
let fb3;
let sum = 0;
let input = 4000000;

while (fb1 < input){
    if(fb1 % 2 == 0){
        sum = sum + fb1;
    }
    fb3 = fb1 + fb2;
    fb1 = fb2;
    fb2 = fb3;
}

console.log(sum); //answer: 4613732